version: '3.8'
services:
  web:
    container_name: web
    hostname: web
    image: web
    build:
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
      context: ./requirements/web
      dockerfile: Dockerfile
    depends_on:
      - db
      - phpmyadmin
    ports:
      - "1505:80"
    networks:
      - camagru
    restart: on-failure

#------------------------------DATABASE------------------------------#
  db:
    container_name: db
    hostname: db
    image: db
    build:
      context: ./requirements/db
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: camagru
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - camagru
    restart: on-failure
    volumes:
      - db_data:/var/lib/db/data

  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin
    build:
      context: ./requirements/phpmyadmin
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - camagru
    ports:
      - "5555:80"
    restart: on-failure
    volumes:
      - phpmyadmin_data:/var/www/html

#------------------------------SMTP------------------------------#
  smtp:
    container_name: smtp
    hostname: smtp
    image: smtp
    build:
      context: ./requirements/smtp
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    networks:
      - camagru
    ports:
      - 25:25  
    restart: on-failure

#------------------------------NETWORKS------------------------------#
networks:
  camagru:
    driver: bridge

#------------------------------VOLUMES------------------------------#
volumes:
  db_data:
    driver: local
  phpmyadmin_data:
    driver: local